### ISSUE TITLE
timeout error in batch mode producing pdf

### ISSUE THREAD

**Issue by jzook** [svviz/svviz#32]
When running with the GIAB AJ trio PacBio data in batch mode, I get a timeout error when converting the first site to pdf. 

Here's the vcf line:

```
9   108906620   .   .   TGCTAAGGTGATATTTGAAAGTAATATTCAGATTGATTTGGTGGAGAGGGCATGTGTGACTTTGGATCTGGGGCAACTGTCATTGAGAGTAATCTTAGAAATAAAGTTTATATTCTTAAAAAAAAGTGGCTGGAGGCCAAGACGTATGTTCAAGTCCTCAAATGCCTGTTGCTCATGTATTGGTATTGATATGTGTCTAGACTAAGAGATCCTTCCAGAAACTACTTCAGAAATCTAGAAGTTACTTCTGAAATTGATAGCATAATAGCAGGTTCTGAAAAACATTCAAATGTAGATTCAAATCCTTCATTTCCTGAGTAGTTATTACTTTGGGCAAGTTATTTACTTTTCACAACTTGGCTTTTTCATCTATAAAATGGAGGTGAAAATATTTAACATAAAAATTATTGTAAGATTAAAATGAGGTAATTTATGCACTGTACAAGATGCAATCCTAAAATAACAAAGTTACTCAGTGAATTGTAGATATTATTATCATTATTTTTTCTTCTTCTTTAGACCCTTAAATTTTTTGTTCAAAATATCTGGCTACTTATTTGTCATAGCTGTGTCTCTAACACCCTTACAGAGATAGGTATTTTATAGACTGTCAATATGTTTTTTTAAAATGGTGATCACAGCGTTACTGACATTTATTAAAATGGTTACTTGCCTTTGGAAACTTTCACTATTGTCAGGAAGAACCTAAACCAAAAAATCTAGCATCAACCAACAATCTACAGTTGCTGATATCACTGGTGCTTTTTTATTTTTATCATTCTATTAGTCAAAGTTTTCTATGTGGTAATATGTCCCTTCAAATATTAACTGAGGCTAATATTTATGGAGTATTTACTAGGTGCTTGATCTATGTCAGGTAACAAAAACACTGAGTTAAACCCTGTTTGGGAAGCACATAATGTGAGGACATCCTGCCAAGCATAAAGCATTATGAGAATGACTGCA  .   .   SVTYPE=INS
```

Here's the error:

```
 + BWA-MEM_HG002_m:alt total 100.0% [===========] left:0.4s 0:100% 1:100% 2:100% 3:100% 4:100% 5:100% 6:100% 7:100%
 Time to realign: 331.5s
* Assigning reads to most probable alleles *
 Time for disambiguation: 0.01s
 Time for disambiguation: 0.01s
 Time for disambiguation: 0.02s
* Rendering tracks *
 * Generating dotplots *
********** 0
  Couldn't run recommended dot-plot helper-program yass: 'No module named rpy2'
* Exporting views *
2015-12-14 11:01:13.695 webkitToPDF[23042:d07] Input:  /var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/tmpp5QmWP/original.svg
2015-12-14 11:01:13.696 webkitToPDF[23042:d07] Output: /var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/tmpp5QmWP/converted.pdf
2015-12-14 11:12:57.534 webkitToPDF[23042:d07] Error while loading page: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x108903a10 {NSUnderlyingError=0x10340d640 "The request timed out.", NSErrorFailingURLStringKey=file:///var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/tmpp5QmWP/original.svg, NSErrorFailingURLKey=file:///var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/tmpp5QmWP/original.svg, NSLocalizedDescription=The request timed out.}
Traceback (most recent call last):
  File "/Users/jzook/anaconda/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.4.0', 'console_scripts', 'svviz')()
  File "/Users/jzook/anaconda/lib/python2.7/site-packages/svviz/app.py", line 341, in main
    run(sys.argv)
  File "/Users/jzook/anaconda/lib/python2.7/site-packages/svviz/app.py", line 321, in run
    runDirectExport(dataHub)
  File "/Users/jzook/anaconda/lib/python2.7/site-packages/svviz/app.py", line 178, in runDirectExport
    exportData = export.convertSVG(exportData, exportFormat, converter)
  File "/Users/jzook/anaconda/lib/python2.7/site-packages/svviz/export.py", line 310, in convertSVG
    exportData = _convertSVG_webkitToPDF(inpath, outpath, outformat)
  File "/Users/jzook/anaconda/lib/python2.7/site-packages/svviz/export.py", line 328, in _convertSVG_webkitToPDF
    return open(outpath).read()
IOError: [Errno 2] No such file or directory: '/var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/tmpp5QmWP/converted.pdf' 
```

**Comment by nspies** [comment]
Hrm, this works for me. Can you give me the exact command you used to run svviz?

**Comment by jzook** [comment]
Interesting.  I tried 60x illumina paired end seq with the same SVs, and
all worked except a 100kb site, which got this same error.  Even small ones
seem to get this error for the PacBio trio data.  Here's the command:

svviz -t batch --summary
/Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_svvizsummary.tsv --export
/Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_svvizfigs -b
/Volumes/UHTS1/AJPacBio/HG003/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG003_merged_11_12.sort.bam
-b
/Volumes/UHTS1/AJPacBio/HG004/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG004_merged_11_12.sort.bam
-b
/Volumes/UHTS1/AJPacBio/HG002/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG002_merged_11_12.sort.bam
--aln-quality 0.2 --dotplots /Volumes/SSD960/references/human_g1k_v37.fasta
/Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_test.vcf

**Comment by nspies** [comment]
Can you try it with either svg format or with the `--skip-cigar` option on? I'm guessing what's happening is that the pacbio data has so many sequence errors that the renderings aren't able to be converted when the mismatches/indels are shown.

**Comment by jzook** [comment]
--skip-cigar seems to have fixed the issue with creating pdfs for pacbio reads.  Thanks!
