### ISSUE TITLE
'module' object has no attribute 'SafeFunction'

### ISSUE THREAD

**Issue by fritzsedlazeck** [svviz/svviz#42]
Hi,
I installed svviz on our cluster (locally and in the virtual environment) as well as on my laptop. When I try to run the demo on any of them I get an error in the end of run (see below).
Anny suggestions?
Cheers
Fritz

```
..........
 number of reads found: 1778
 Found 5,898 reads across 3 samples for a total of 531,714 nt
* Realigning reads *
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.5.0', 'console_scripts', 'svviz')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/app.py", line 350, in main
    run(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/app.py", line 319, in run
    runRemap(dataHub)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/app.py", line 116, in runRemap
    sample.alnCollections = remap.do_realign(dataHub, sample)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/remap.py", line 187, in do_realign
    jobName=name.format("ref"))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/remap.py", line 147, in do1remap
    verbose=verbose, processes=processes, name=jobName))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svviz/multiprocessor.py", line 64, in map
    result = pool.apply_async(joblib.parallel.SafeFunction(_map),
AttributeError: 'module' object has no attribute 'SafeFunction'

```

**Comment by nspies** [comment]
Hi Fritz,

This is related to #41. I've removed the joblib dependency -- can you confirm that it's working for you now? You'll need to install the latest source version:

```
sudo pip install -U git+git://github.com/svviz/svviz.git
```

I'll release a new version if it seems to work for you.

Noah

**Comment by fritzsedlazeck** [comment]
Hi Noah,
thanks for the fast reply. Works!
Cheers
Fritz
