### ISSUE TITLE
Cannot load demo (OSX)

### ISSUE THREAD

**Issue by ranasats** [svviz/svviz#49]
Hey,

I run into this error every time I try to run the demo.
```
Couldn't find example data in current working directory (svviz-examples/example1). Shall I download it and decompress it into the current working directory? Y/n:y
Traceback (most recent call last):
  File "/usr/local/bin/svviz", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 371, in main
    run(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 285, in run
    args = commandline.parseArgs(args)
  File "/usr/local/lib/python2.7/site-packages/svviz/commandline.py", line 104, in parseArgs
    inputArgs = checkDemoMode(args)
  File "/usr/local/lib/python2.7/site-packages/svviz/commandline.py", line 84, in checkDemoMode
    cmd = demo.loadDemo(which, args.auto_download)
  File "/usr/local/lib/python2.7/site-packages/svviz/demo.py", line 78, in loadDemo
    if not checkForDemo(which, autoDownload):
  File "/usr/local/lib/python2.7/site-packages/svviz/demo.py", line 68, in checkForDemo
    """Shall I download it and decompress it into the current working directory? Y/n:""".format(which))
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```

Same thing happens when I do Y, n, N, or just enter. I've tried installing/uninstalling, and using pip and pip3.6.

**Comment by nspies** [comment]
Thanks for your bug report.

I think I've fixed this in the latest version on github. You can try installing this development version by running `pip install -U git+git://github.com/svviz/svviz.git`. Let me know if this fixes your problem.

**Comment by ranasats** [comment]
Perfect. Fixed.

Thanks!
